# Generated by Django 4.0.3 on 2022-03-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
