# Generated by Django 3.1.7 on 2022-03-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_models', '0005_message_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='tg_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
