# Generated by Django 3.1.7 on 2022-03-19 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220319_1853'),
        ('chat_models', '0006_chat_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='viewers',
            field=models.ManyToManyField(null=True, related_name='viewers_chats', to='users.User'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_chats', to='users.user'),
        ),
    ]
