# Generated by Django 3.1.7 on 2022-03-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_models', '0007_auto_20220319_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='tg_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
