# Generated by Django 3.1.7 on 2022-03-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_models', '0008_auto_20220320_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='tg_id',
            field=models.CharField(default='1', max_length=100, unique=True),
        ),
    ]
