# Generated by Django 3.1.7 on 2022-03-19 21:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat_models', '0009_auto_20220320_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='tg_id',
            field=models.CharField(default=uuid.uuid1, max_length=100, unique=True),
        ),
    ]
